server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/friendlyLib
    username: admin
    password: admin

friendlylib:
  jwt:
    accessTokenSecret: password
    refreshTokenSecret: refreshPassword
    issuer: FriendlyLib
    tokenExpirationTime: 1
    refreshTokenExpirationTime: 60
    rememberMeExpirationTime: 7200

